require 'simplecov'

# create code coverage report
SimpleCov.start

# pre-loads all files in the lib directory, so we don't need to load them in each spec file
files_to_load = Dir["#{File.dirname(__FILE__)}/../lib/**/*.rb"]
files_to_load.reject { |f| f.include?("playground") }.each { |f| require f }

# default rspec config generated by rspec --init
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups
end
